# Generated by Django 2.2 on 2020-08-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='good',
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='webapp.Product', verbose_name='Товары'),
            preserve_default=False,
        ),
    ]
